clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    models:
      - name: gemma3:12b
        max_input_tokens: 128000
        supports_function_calling: true
      - name: gemma3:27b
        max_input_tokens: 128000
        supports_function_calling: true
