# theme = "base16_transparent"
# theme = "term16_dark"
theme = "base16_enhanced"

[editor]
true-color = true
idle-timeout = 0
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
# mapped to keys.normal.space l
# display-inlay-hints = true

[editor.smart-tab]
enable = true
supercede-menu = false

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it

[keys.normal]
# "*" = ["search", "insert_word", "submit_search"] # broken
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.space]
l = ":toggle-option lsp.display-inlay-hints"
q = ":write"
e = "file_explorer_in_current_buffer_directory"
E = ":sh zellij run -c -f -x 1% -y 1% --width 99% --height 98% -- nu $ZELLIX_MOD/yazi.nu"
z = ":write-all"

[keys.normal.space.w]
c = ":bc" # close buffer

[keys.insert]
S-tab = "move_parent_node_start"
C-a = "completion"

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

# Zellix
[keys.normal.space.f]
f = ":sh zellij run -c -f -x 1% -y 1% --width 98% --height 98% -- nu $ZELLIX_MOD/broot.nu"
e = "file_picker"
w = ":sh zellij run -c -f -x 1% -y 1% --width 98% --height 98% -- nu $ZELLIX_MOD/fzf.nu"

# [keys.normal.space.l]
# a = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- nu $ZELLIX_MOD/ai.nu"
# b = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- nu $ZELLIX_MOD/bacon.nu"
 
