[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
indent = { tab-width = 2, unit = "\t" }

[language-server.rust-analyzer.config.check]
check = {command = "cargo", extraArgs = ["clippy"]}
