[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "rustfmt", args = ["--edition", "2024"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nix fmt" }
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "python"
diagnostic-severity = "info"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.rust-analyzer.config.procMacro]
# https://book.leptos.dev/getting_started/leptos_dx.html#2-editor-autocompletion-inside-component-and-server
ignored = { leptos_macro = [
  # Optional:
  # "component",
  # "server"
] }

[language-server.rust-analyzer.config.check]
check = { command = "cargo", extraArgs = ["clippy"] }

[language-server.pylsp.config.pylsp.plugins]
pycodestyle = { ignore = ["E501"], maxLineLength = 120 }

[language-server.ruff]
command = "ruff"
config = { lint = { ignore = ["E501", "W293"] } }
